### ISSUE TITLE
Error while switching from one model to anouther 

### ISSUE THREAD

**Issue by ajayahara** [gwendall/use-media-models#1]
import { useEffect, useRef } from "react";
import { NavLink } from "react-router-dom";
import { useCamera, useMediapipe } from "use-media-models";

export const HandDetection = () => {
    const videoRef = useRef(null);
    const canvasRef = useRef(null);
    const poseCount = useRef(0);
    const { startCamera , isCameraStarted} = useCamera(videoRef);
    const { startModel } = useMediapipe("handLandmarker", {
        onResults: (results) => {
            if (!canvasRef.current && !videoRef.current) return;
            poseCount.current++;
            const canvas = canvasRef.current;
            const video = videoRef.current;
            const ctx = canvas.getContext("2d");
            canvas.width = video.offsetWidth;
            canvas.height = video.offsetHeight;
            ctx.clearRect(0, 0, canvas.width, canvas.height);

            drawLandmarks(canvas, ctx, results.landmarks[0]);
            drawLandmarks(canvas, ctx, results.landmarks[1]);
        },
    });

    useEffect(() => {
        startCamera().then(({ stream }) => startModel({ stream }));

        const resizeCanvas = () => {
            if (canvasRef.current && videoRef.current) {
                canvasRef.current.width = videoRef.current.offsetWidth;
                canvasRef.current.height = videoRef.current.offsetHeight;
            }
        };

        window.addEventListener("resize", resizeCanvas);
        resizeCanvas();

        return () => {
            window.removeEventListener("resize", resizeCanvas);
        };
    }, []);

    useEffect(() => {
        // Log the pose count every second and reset
        const intervalId = setInterval(() => {
            console.log("Poses detected in last second:", poseCount.current);
            poseCount.current = 0;
        }, 1000);

        return () => clearInterval(intervalId); // Clean up interval on unmount
    }, []);

    const drawLandmarks = (canvas, ctx, landmarks) => {
        if (!landmarks) return;
        // Draw landmarks
        landmarks.forEach((landmark, index) => {
            const x = landmark.x * canvas.width;
            const y = landmark.y * canvas.height;
            ctx.beginPath();
            ctx.arc(x, y, 5, 0, 2 * Math.PI); // Slightly larger circles
            ctx.fillStyle = 'blue' // Thumb red, others blue
            ctx.fill();
        });
    };
    console.log("isCameraStarted", isCameraStarted);
    return (
        <>
            <div className="h-1/2 aspect-video relative">
                <video
                    ref={videoRef}
                    style={{
                        position: "absolute",
                        top: 0,
                        left: 0,
                        width: "100%",
                        height: "100%",
                        objectFit: "cover",
                        backgroundColor: "white",
                    }}
                    autoPlay
                    playsInline
                />
                <canvas
                    ref={canvasRef}
                    style={{
                        position: "absolute",
                        top: 0,
                        left: 0,
                        width: "100%",
                        height: "100%",
                    }}
                />
            </div>
            <NavLink to="/" className='underline text-purple-800'>Go Back</NavLink>
        </>
    );
}
import { useEffect, useRef } from "react";
import { NavLink } from "react-router-dom";
import { useCamera, useMediapipe } from "use-media-models";

export const PoseDetection = () => {
    const videoRef = useRef(null);
    const canvasRef = useRef(null);
    const poseCount = useRef(0);
    const { startCamera, isCameraStarted } = useCamera(videoRef);
    const { startModel } = useMediapipe("pose", {
        onResults: (results) => {
            if (canvasRef.current && videoRef.current) {
                const canvas = canvasRef.current;
                const video = videoRef.current;
                const ctx = canvas.getContext("2d");

                // Set canvas dimensions to match the video element
                canvas.width = video.offsetWidth;
                canvas.height = video.offsetHeight;

                // Clear previous drawings
                ctx.clearRect(0, 0, canvas.width, canvas.height);

                // Flip the canvas horizontally
                ctx.save();
                ctx.scale(-1, 1); // Horizontal flip
                ctx.translate(-canvas.width, 0); // Move drawing back into view

                if (results.poseLandmarks) {
                    poseCount.current++;
                    // Draw skeleton lines between key landmarks
                    const connections = [
                        [11, 13], [13, 15], // Left arm: shoulder to elbow, elbow to wrist
                        [12, 14], [14, 16], // Right arm: shoulder to elbow, elbow to wrist
                        [11, 12], // Shoulders
                        [11, 23], [12, 24], // Torso: shoulders to hips
                        [23, 24], // Hips
                        [23, 25], [25, 27], // Left leg: hip to knee, knee to ankle
                        [24, 26], [26, 28], // Right leg: hip to knee, knee to ankle
                    ];

                    ctx.strokeStyle = "blue";
                    ctx.lineWidth = 2;

                    connections.forEach(([start, end]) => {
                        const startLandmark = results.poseLandmarks[start];
                        const endLandmark = results.poseLandmarks[end];

                        ctx.beginPath();
                        ctx.moveTo(startLandmark.x * canvas.width, startLandmark.y * canvas.height);
                        ctx.lineTo(endLandmark.x * canvas.width, endLandmark.y * canvas.height);
                        ctx.stroke();
                    });

                    // Draw landmarks as circles
                    results.poseLandmarks.forEach((landmark) => {
                        ctx.beginPath();
                        ctx.arc(
                            landmark.x * canvas.width,
                            landmark.y * canvas.height,
                            5,
                            0,
                            2 * Math.PI
                        );
                        ctx.fillStyle = "red";
                        ctx.fill();
                    });
                }

                // Restore the canvas context after drawing
                ctx.restore();
            }
        },
    });

    useEffect(() => {
        startCamera().then(({ stream }) => startModel({ stream }));

        const resizeCanvas = () => {
            if (canvasRef.current && videoRef.current) {
                canvasRef.current.width = videoRef.current.offsetWidth;
                canvasRef.current.height = videoRef.current.offsetHeight;
            }
        };

        window.addEventListener("resize", resizeCanvas);
        resizeCanvas();

        return () => {
            window.removeEventListener("resize", resizeCanvas);
        };
    }, []);

    useEffect(() => {
        // Log the pose count every second and reset
        const intervalId = setInterval(() => {
            console.log("Poses detected in last second:", poseCount.current);
            poseCount.current = 0;
        }, 1000);

        return () => clearInterval(intervalId); // Clean up interval on unmount
    }, []);
    console.log("isCameraStarted", isCameraStarted);
    return (
        <>
            <div className="h-1/2 aspect-video relative">
                <video
                    ref={videoRef}
                    style={{
                        position: "absolute",
                        top: 0,
                        left: 0,
                        width: "100%",
                        height: "100%",
                        objectFit: "cover",
                        backgroundColor: "white",
                    }}
                    autoPlay
                    playsInline
                />
                <canvas
                    ref={canvasRef}
                    style={{
                        position: "absolute",
                        top: 0,
                        left: 0,
                        width: "100%",
                        height: "100%",
                    }}
                />
            </div>
            <NavLink to="/" className='underline text-purple-800'>Go Back</NavLink>
        </>
    );
}
Bug +1: Error appearing when i am switching pose detection page to hand detection page:-
pose_solution_simd_wasm_bin.js:9 Uncaught (in promise) RuntimeError: Aborted(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name))
    at abort (pose_solution_simd_wasm_bin.js:9:17640)
    at Object.get (pose_solution_simd_wasm_bin.js:9:7759)
    at VM492 vision_wasm_internal.js:9:2807
    at use-media-models.js?v=7f47133e:2798:179
    at async zo (use-media-models.js?v=7f47133e:2795:19)
   
Bug +2: Camera is not turning off while leaving the detection component

**Comment by ajayahara** [comment]
Bug +3: performance issue.
Even if I fixed the error while switching between pose and hand detector the rate of detection decreased by half from the previous.
